name: 部署 Next.js 应用

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v2

      - name: 安装 SSH 密钥
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: 添加服务器到已知主机
        run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: 安装 rsync
        run: sudo apt-get install -y rsync

      - name: 使用 rsync 部署文件
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='*.log' \
            --exclude='.vscode' \
            --exclude='.idea' \
            --exclude='README.md' \
            --exclude='*.test.*' \
            --exclude='coverage' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/beicun/

      - name: 执行服务器命令
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/beicun
            # 创建日志目录
            mkdir -p logs
            # 复制环境变量文件
            cp .env.production
            # 安装依赖并构建
            yarn install
            npx prisma generate
            yarn run build
            # 重启应用
            pm2 reload ecosystem.config.js || pm2 start ecosystem.config.js